[package]
name = "gtars-r"
version = "0.6.0"
edition = "2021"

[lib]
name = "gtars"
crate-type = ["staticlib"]

[dependencies]
extendr-api = { git = "https://github.com/extendr/extendr", branch = "main" }
anyhow = "1.0.82"
gtars-core = { git = "https://github.com/databio/gtars", branch = "dev" }
gtars-io = { git = "https://github.com/databio/gtars", branch = "dev" }
gtars-igd = { git = "https://github.com/databio/gtars", branch = "dev" }
gtars-refget = { git = "https://github.com/databio/gtars", branch = "dev" }
gtars-genomicdist = { git = "https://github.com/databio/gtars", branch = "dev" }
gtars-tokenizers = { git = "https://github.com/databio/gtars", branch = "dev", features = ["huggingface"] }
serde_json = "1.0"
